apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}