apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    {{- include "shop.labels" (dict "root" . "name" "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "shop.selectorLabels" (dict "root" . "name" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop.labels" (dict "root" . "name" "worker") | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - {name: http, containerPort: 8080}
          env:
            - {name: APP_VERSION, value: {{ .Values.worker.image.tag | quote }}}
            - {name: HEALTH_FAIL, value: {{ .Values.worker.healthFail | quote }}}
            {{- include "shop.dbEnv" . | nindent 12 }}
          readinessProbe:
            httpGet: {path: /health, port: 8080}
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet: {path: /health, port: 8080}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: [ALL]}
