apiVersion: v1
kind: Pod
metadata:
  name: no-limits
  labels:
    app.kubernetes.io/name: no-limits
    team: shop
spec:
  containers:
    - name: app
      image: registry.shop.local/shop/api:1.0
      securityContext:
        runAsNonRoot: true
