apiVersion: v1
kind: Pod
metadata:
  name: privileged
  labels:
    app.kubernetes.io/name: privileged
    team: shop
spec:
  containers:
    - name: app
      image: registry.shop.local/shop/api:1.0
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        privileged: true
